### ISSUE TITLE
how to get the dataset for RE

### ISSUE THREAD

**Issue by ouyang982020** [asahi417/relbert#2]

**Comment by asahi417** [comment]
@ouyang982020 
Hi you can find the datasets used in our paper in the following links:
- [analogy](https://github.com/asahi417/AnalogyTools/releases/download/0.0.0/analogy_test_dataset.zip)
- [relation classification](https://github.com/asahi417/AnalogyTools/releases/download/0.0.0/lexical_relation_dataset.zip)

To know more about the dataset, you may also want to take a look [here](https://github.com/asahi417/AnalogyTools).
