### ISSUE TITLE
Problem loading models

### ISSUE THREAD

**Issue by niteshroyal** [asahi417/relbert#4]
I installed RELBERT using the command:

$ pip install relbert

I am getting the following error when I load models:

>>> from relbert import RelBERT
>>> model = RelBERT('asahi417/relbert-roberta-large')
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 840/840 [00:00<00:00, 742kB/s]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/c.scmnk4/miniconda3/lib/python3.10/site-packages/relbert/lm.py", line 133, in __init__
    self.template_mode = self.model_config.relbert_config['template_mode']
KeyError: 'template_mode'

Could you please tell how to resolve the issue?

**Comment by asahi417** [comment]
Hi, sorry but those models are not compatible, so please use `relbert/relbert-roberta-large` instead.

**Comment by niteshroyal** [comment]
Hi,

Now, I am getting this error: 

Traceback (most recent call last):
  File "/home/nitesh/PycharmProjects1/pythonProject/research/vector_space_rules/dataset.py", line 59, in __init__
    self.model = RelBERT('relbert/relbert-roberta-large')
  File "/home/nitesh/PycharmProjects1/pythonProject/research/vector_space_rules/relbert/relbert/lm.py", line 149, in __init__
    self.mode = model_config.relbert_config['mode']
KeyError: 'mode'

Could you please check it?

**Comment by asahi417** [comment]
Can you update the relbert version? We changed the model configuration recently, and fixed the library accordingly, so you need the latest relbert.

**Comment by asahi417** [comment]
The latest relbert at the moment is version 2.0.1 btw.
https://pypi.org/project/relbert/2.0.1/

**Comment by niteshroyal** [comment]
After installing version 2.0.1, I get this error:

>>> from relbert import cosine_similarity
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'cosine_similarity' from 'relbert' (/home/nitesh/.local/lib/python3.10/site-packages/relbert/__init__.py)
>>>

**Comment by asahi417** [comment]
So at least the model loading has no issue now, correct?

**Comment by asahi417** [comment]
Ok, fixed the issue and pushed as version 2.0.2 now

**Comment by niteshroyal** [comment]
The issue is resolved. 

However, I have one more question. 

Is the RELBert model now changed? That is, now does it produce vectors different from the previous RELBert model for the same word pairs?

**Comment by asahi417** [comment]
Assuming the you used `asahi417/relbert-roberta-large`, the new one is a better model and yes it has a different embedding space from the old one.

**Comment by niteshroyal** [comment]
Now, it is not possible to use: asahi417/relbert-roberta-large

Could you please give the option to use the old model also?

**Comment by niteshroyal** [comment]
I need the vectors generated by the old model as I was analyzing those vectors.

**Comment by asahi417** [comment]
I shared the old model in the below link.
https://huggingface.co/research-backup/relbert-old

You can use the model as follows.
```
from relbert import RelBERT
model = RelBERT("research-backup/relbert-old")
```

However, do not expect it to be maintained. We may update the relbert library for better utility in the future, and we won't check the compatibility with this model upon the update, so please make sure that you're using the right version of relbert when you use this old model.

**Comment by niteshroyal** [comment]
Thanks. It is working now.
