### ISSUE TITLE
P-tuning

### ISSUE THREAD

**Issue by cxy1122** [asahi417/relbert#7]
Hello, I am a beginner in NLP. First of all, thank you for open sourcing RelBERT, it is a great model and performs well in relation classification. Recently, I wanted to use your RelBERT with P-tuningV2, but I did not find any information about using P-tuning in the repository. Could you please let me know if I missed it or if this part has not been open sourced?

**Comment by asahi417** [comment]
Hi, p-tuning experiment we have done in our EMNLP21 paper can be found here. I put it aside and keep it in other branch as we decided to not explore this direction anymore.

https://github.com/asahi417/relbert/tree/emnlp_2021#reproduce-the-experiments

**Comment by cxy1122** [comment]
> Hi, p-tuning experiment we have done in our EMNLP21 paper can be found here. I put it aside and keep it in other branch as we decided to not explore this direction anymore.
> 
> https://github.com/asahi417/relbert/tree/emnlp_2021#reproduce-the-experiments

Thank you very much for your response. I have another question. I noticed from the paper that when using P-tuning, [MASK] is not set and the template is learned automatically and directly inputted into the language model to obtain embeddings. I would like to ask if you did the same thing. If so, do you think that setting [MASK] is not very important in this case?

**Comment by cxy1122** [comment]
> Hi, p-tuning experiment we have done in our EMNLP21 paper can be found here. I put it aside and keep it in other branch as we decided to not explore this direction anymore.
> 
> https://github.com/asahi417/relbert/tree/emnlp_2021#reproduce-the-experiments

Thank you very much for your response. I have another question. I noticed from the paper that when using P-tuning, [MASK] is not set and the template is learned automatically and directly inputted into the language model to obtain embeddings. I would like to ask if you did the same thing. If so, do you think that setting [MASK] is not very important in this case?

**Comment by asahi417** [comment]
Thanks for reading our paper in detail! You're right that we don't use a mask token in p-tuning and auto-prompt, and indeed you can use a mask token in p-tuning. In the paper, we only tried p-tuning with templates without a mask token, mainly to reduce the optimization cost. In p-tuning, we have to try different templates, varying the number of first/middle/last special tokens, which already introduces a lot of templates to test. If we wanted to test a template with a mask token, we then needed to every possible position of a mask token in each template, that would result in an even larger amount of templates.
